import type { Metadata } from "next";
import {  Lobster_Two, Poppins, Rancho } from "next/font/google";
import "./globals.css";
import Footer from "./components/Footer";

const lobsterTwo = Lobster_Two({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-subtitle',
});

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  variable: '--font-primaryFont',
});

const rancho = Rancho({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-heroTitle',
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${lobsterTwo.variable} ${poppins.variable} ${rancho.variable} antialiased`}
      >
        <div className="">
        {children}
        </div>
        <Footer />
      </body>
    </html>
  );
}
